# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-07-02 07:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer_bank_detail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(max_length=30)),
                ('customer_mobile_no', models.IntegerField()),
                ('customer_address', models.CharField(max_length=200)),
                ('bank_account_no', models.IntegerField()),
                ('ifsc_code', models.IntegerField()),
            ],
        ),
    ]
