# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-07-03 11:54
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('bank_account', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bank_account',
            name='user',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
