# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-07-02 07:49
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bank_account', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer_bank_detail',
            name='customer_address',
        ),
    ]
