# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-07-02 07:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank_account', '0002_remove_customer_bank_detail_customer_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer_bank_detail',
            name='branch_name',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
    ]
