# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-07-02 08:17
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bank_account', '0004_auto_20180702_0813'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='bank_details',
            new_name='Customer_bank_detail',
        ),
        migrations.RenameField(
            model_name='customer_bank_detail',
            old_name='account_no',
            new_name='account_number',
        ),
    ]
