# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-07-02 08:27
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('bank_account', '0005_auto_20180702_0817'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer_bank_detail',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='customer_bank_detail',
            name='modified',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
