# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-07-02 09:31
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bank_account', '0007_order'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Customer_bank_detail',
            new_name='bank_account',
        ),
    ]
