# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-07-02 11:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank_account', '0009_auto_20180702_1034'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bank_account',
            options={'get_latest_by': 'modified', 'ordering': ('-modified', '-created')},
        ),
        migrations.AddField(
            model_name='bank_account',
            name='completed',
            field=models.BooleanField(default=False),
        ),
    ]
