# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-07-02 13:23
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bank_account', '0010_auto_20180702_1116'),
    ]

    operations = [
        migrations.DeleteModel(
            name='order',
        ),
        migrations.AlterModelOptions(
            name='bank_account',
            options={},
        ),
        migrations.RemoveField(
            model_name='bank_account',
            name='completed',
        ),
        migrations.RemoveField(
            model_name='bank_account',
            name='created',
        ),
        migrations.RemoveField(
            model_name='bank_account',
            name='modified',
        ),
    ]
