# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-07-03 09:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='contact_number',
            field=models.IntegerField(default='123456'),
        ),
        migrations.AddField(
            model_name='user',
            name='first_name',
            field=models.CharField(default='abc', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='last_name',
            field=models.CharField(default='asdf', max_length=255),
            preserve_default=False,
        ),
    ]
